stages:
  - uhd
  - gnuradio
  - fpga

.conditionals: &conditionals
  refs:
    - master
    - branches
    - web

.uhd-build: &uhd-build
  - mkdir build
  - cd build
  - cmake ../ -DENABLE_UHD=1 -DENABLE_GNURADIO=0
  - make -j10

.gnuradio-build: &gnuradio-build
  - mkdir build
  - cd build
  - cmake ../ -DENABLE_UHD=1 -DENABLE_GNURADIO=1
  - make -j10

build-uhd-master:
  stage: uhd
  image: theseuscores/uhd:master-rfnoc-all
  script: *uhd-build
  only: *conditionals

build-uhd-3.13:
  stage: uhd
  image: theseuscores/uhd:UHD-3.13-rfnoc-all
  script: *uhd-build
  only: *conditionals

build-gnuradio-maint-uhd-master:
  stage: gnuradio
  image: theseuscores/gnuradio:maint-3.7-UHD-master-rfnoc
  script: *gnuradio-build
  only: *conditionals

build-gnuradio-maint-uhd-3.13:
  stage: gnuradio
  image: theseuscores/gnuradio:maint-3.7-UHD-3.13-rfnoc
  script: *gnuradio-build
  only: *conditionals

fpga-test:
  stage: fpga
  before_script:
    - rm -rf ../uhd-fpga && git clone -b UHD-3.13 https://github.com/EttusResearch/fpga.git ../uhd-fpga
    - source /opt/Xilinx/Vivado/2017.4/settings64.sh
  script:
    - cd fpga-rfnoc/testbenches
    - for d in ./*/ ; do (cd "$d" && pwd && make clean && ./runtestbench.sh); done
  only:
    - master
    - merge_requests
    - web
  tags:
    - vivado
