stages:
  - uhd
  - gnuradio
  - fpga

.conditionals: &conditionals
  refs:
    - master
    - branches
    - web

.uhd-build: &uhd-build
  - mkdir build
  - cd build
  - cmake ../ -DENABLE_UHD=1 -DENABLE_GNURADIO=0
  - make -j10

.gnuradio-build: &gnuradio-build
  - mkdir build
  - cd build
  - cmake ../ -DENABLE_UHD=1 -DENABLE_GNURADIO=1
  - make -j10

.fpga-script: &fpga-script
  - rm -rf ../uhd-fpga && git clone -b UHD-3.13 https://github.com/EttusResearch/fpga.git ../uhd-fpga
  - export UHD_FPGA_DIR=`pwd`/../uhd-fpga
  - source /opt/Xilinx/Vivado/2017.4/settings64.sh
  - cd fpga-rfnoc/testbenches
  - for d in ./*/ ; do (cd "$d" && pwd && make clean && ./runtestbench.sh); done

build-uhd-3.13:
  stage: uhd
  image: theseuscores/uhd:UHD-3.13-rfnoc-all
  script: *uhd-build
  only: *conditionals

build-uhd-3.14:
  stage: uhd
  image: theseuscores/uhd:UHD-3.14-rfnoc-all
  script: *uhd-build
  only: *conditionals

build-gnuradio-maint-uhd-3.13:
  stage: gnuradio
  image: theseuscores/gnuradio:maint-3.7-UHD-3.13-rfnoc
  script: *gnuradio-build
  only: *conditionals

build-gnuradio-maint-uhd-3.14:
  stage: gnuradio
  image: theseuscores/gnuradio:maint-3.7-UHD-3.14-rfnoc
  script: *gnuradio-build
  only: *conditionals

